// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC__6D0DhC9_b9nwXU2HevmYQDAUleimYw',
    appId: '1:1020433224250:web:63b88420d452f073bcdb03',
    messagingSenderId: '1020433224250',
    projectId: 'anaam--app',
    authDomain: 'anaam--app.firebaseapp.com',
    databaseURL: 'https://anaam--app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anaam--app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtdoKB_pjdS_t90OMjYlZQJ6WrkI4DxJU',
    appId: '1:1020433224250:android:ac2c3c7f233e525ebcdb03',
    messagingSenderId: '1020433224250',
    projectId: 'anaam--app',
    databaseURL: 'https://anaam--app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anaam--app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUcgNImWuElWaWmy_KKsKs5yYKota80k8',
    appId: '1:1020433224250:ios:88c5e14a1b5fb294bcdb03',
    messagingSenderId: '1020433224250',
    projectId: 'anaam--app',
    databaseURL: 'https://anaam--app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anaam--app.appspot.com',
    androidClientId: '1020433224250-p02sm8cab73ajfe46170mp0lqa14du3u.apps.googleusercontent.com',
    iosClientId: '1020433224250-oj86mvtsc9vevcps03f4oq7rkqau6nts.apps.googleusercontent.com',
    iosBundleId: 'com.example.anaam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUcgNImWuElWaWmy_KKsKs5yYKota80k8',
    appId: '1:1020433224250:ios:3be317276a899109bcdb03',
    messagingSenderId: '1020433224250',
    projectId: 'anaam--app',
    databaseURL: 'https://anaam--app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'anaam--app.appspot.com',
    androidClientId: '1020433224250-p02sm8cab73ajfe46170mp0lqa14du3u.apps.googleusercontent.com',
    iosClientId: '1020433224250-ketpclcuhp44qd8otqs2q7r91pksjesn.apps.googleusercontent.com',
    iosBundleId: 'com.example.anaam.RunnerTests',
  );
}
